### ISSUE TITLE
Referenced diff is repeated in conversation view of PR

### ISSUE THREAD

**Issue by eudika** [kaz-on/gitbucket-code-highlighter-plugin#2]
## Phenomenon, and how to reproduce

1. Setup GitBucket with this plugin installed.
2. Create a repository, open a PR and make a comment on some code. 
3. In the conversation view, referenced lines of diff are repeated.

<img width="692" alt="img1" src="https://user-images.githubusercontent.com/23283270/130335966-6ee81386-002a-47e7-9071-05e848797bab.png">
<img width="689" alt="img2" src="https://user-images.githubusercontent.com/23283270/130335978-fba6fbb3-9cf5-4bb0-883a-e021e8b51f01.png">

## Cause

1. In this plugin, [each line of diff is wrapped in an extra span](https://github.com/kaz-on/gitbucket-code-highlighter-plugin/blob/710aa8de5da824f7dfdc280e6a919029e222e973/src/main/typescript/modules/highlighter.ts#L279-L280), and highlight.js produces more spans in it.
2. In GitGucket, when posting a comment, [referenced lines are gathered by css selector `td span`](https://github.com/gitbucket/gitbucket/blob/2780fb960516dda2bde95d3f387c93970e7349d7/src/main/twirl/gitbucket/core/repo/commentform.scala.html#L181) from DOM.
3. In the result, `tr.find('td span')` contains several elements, and its `text` returns combined text of these elements.

<img width="666" alt="img3" src="https://user-images.githubusercontent.com/23283270/130336465-2130f386-6f08-4c2c-bbf7-3c7f4b2277fc.png">

**Comment by kaz-on** [comment]
Hi @eudika .
Thanks for reporting the issue!
I have released version 1.2.1 which fixes this problem.
Could you please try this version?

**Comment by eudika** [comment]
@kaz-on
I looked the commit and tried the new version.
The problem seems to be fixed.

I appreciate your great plugin, thanks!
